display_name = "ballotbox"
library_name = "ballotbox"
version = "0.2"
author = "Duncan McGreggor"
author_email = "oubiwann@gmail.com"
license = "BSD"
url = "http://launchpad.net/ballotbox"
description = """A Python library for voting algorithms."""
